// <auto-generated />
using System;
using LAB1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LAB1.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220308121720_step3")]
    partial class step3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.14");

            modelBuilder.Entity("LAB1.Models.InvoiceItemModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Amount")
                        .HasColumnType("REAL");

                    b.Property<int>("IvoiceID")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("IvoiceID");

                    b.ToTable("InvoiceItems");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Amount = 17f,
                            IvoiceID = 3,
                            Price = 87.83f,
                            ProductName = "	Crackers - Water	"
                        },
                        new
                        {
                            ID = 2,
                            Amount = 14f,
                            IvoiceID = 4,
                            Price = 79.02f,
                            ProductName = "	Steam Pan - Half Size Deep	"
                        },
                        new
                        {
                            ID = 3,
                            Amount = 1f,
                            IvoiceID = 1,
                            Price = 92.17f,
                            ProductName = "	Sprouts - Pea	"
                        },
                        new
                        {
                            ID = 4,
                            Amount = 77f,
                            IvoiceID = 1,
                            Price = 92.06f,
                            ProductName = "	Apple - Custard	"
                        },
                        new
                        {
                            ID = 5,
                            Amount = 93f,
                            IvoiceID = 1,
                            Price = 8.05f,
                            ProductName = "	Tamarind Paste	"
                        },
                        new
                        {
                            ID = 6,
                            Amount = 90f,
                            IvoiceID = 5,
                            Price = 90.38f,
                            ProductName = "	Parsley Italian - Fresh	"
                        },
                        new
                        {
                            ID = 7,
                            Amount = 71f,
                            IvoiceID = 3,
                            Price = 3.24f,
                            ProductName = "	Steam Pan - Half Size Deep	"
                        },
                        new
                        {
                            ID = 8,
                            Amount = 33f,
                            IvoiceID = 5,
                            Price = 43.51f,
                            ProductName = "	Mushroom - Crimini	"
                        },
                        new
                        {
                            ID = 9,
                            Amount = 1f,
                            IvoiceID = 5,
                            Price = 51.88f,
                            ProductName = "	Scallops 60/80 Iqf	"
                        },
                        new
                        {
                            ID = 10,
                            Amount = 50f,
                            IvoiceID = 3,
                            Price = 32.92f,
                            ProductName = "	Glass Clear 8 Oz	"
                        },
                        new
                        {
                            ID = 11,
                            Amount = 71f,
                            IvoiceID = 5,
                            Price = 33.12f,
                            ProductName = "	Bagel - Sesame Seed Presliced	"
                        },
                        new
                        {
                            ID = 12,
                            Amount = 77f,
                            IvoiceID = 3,
                            Price = 24.05f,
                            ProductName = "	Mushroom - Enoki, Dry	"
                        },
                        new
                        {
                            ID = 13,
                            Amount = 34f,
                            IvoiceID = 5,
                            Price = 80.34f,
                            ProductName = "	Marjoram - Fresh	"
                        },
                        new
                        {
                            ID = 14,
                            Amount = 4f,
                            IvoiceID = 1,
                            Price = 93.08f,
                            ProductName = "	Veal - Kidney	"
                        },
                        new
                        {
                            ID = 15,
                            Amount = 95f,
                            IvoiceID = 2,
                            Price = 46.69f,
                            ProductName = "	Tortillas - Flour, 12	"
                        },
                        new
                        {
                            ID = 16,
                            Amount = 77f,
                            IvoiceID = 1,
                            Price = 62.66f,
                            ProductName = "	Ecolab - Solid Fusion	"
                        },
                        new
                        {
                            ID = 17,
                            Amount = 99f,
                            IvoiceID = 4,
                            Price = 56.06f,
                            ProductName = "	Marjoram - Fresh	"
                        },
                        new
                        {
                            ID = 18,
                            Amount = 10f,
                            IvoiceID = 4,
                            Price = 38.53f,
                            ProductName = "	Tea - Herbal I Love Lemon	"
                        },
                        new
                        {
                            ID = 19,
                            Amount = 66f,
                            IvoiceID = 1,
                            Price = 53.64f,
                            ProductName = "	Cut Wakame - Hanawakaba	"
                        },
                        new
                        {
                            ID = 20,
                            Amount = 19f,
                            IvoiceID = 5,
                            Price = 78.31f,
                            ProductName = "	Lamb - Shoulder, Boneless	"
                        },
                        new
                        {
                            ID = 21,
                            Amount = 66f,
                            IvoiceID = 3,
                            Price = 85.09f,
                            ProductName = "	Wine - Ej Gallo Sierra Valley	"
                        },
                        new
                        {
                            ID = 22,
                            Amount = 54f,
                            IvoiceID = 5,
                            Price = 98.37f,
                            ProductName = "	Crab - Meat Combo	"
                        },
                        new
                        {
                            ID = 23,
                            Amount = 69f,
                            IvoiceID = 4,
                            Price = 83.26f,
                            ProductName = "	Cheese - Brie,danish	"
                        },
                        new
                        {
                            ID = 24,
                            Amount = 84f,
                            IvoiceID = 4,
                            Price = 77.14f,
                            ProductName = "	Squash - Guords	"
                        },
                        new
                        {
                            ID = 25,
                            Amount = 22f,
                            IvoiceID = 5,
                            Price = 40.23f,
                            ProductName = "	Bag - Bread, White, Plain	"
                        },
                        new
                        {
                            ID = 26,
                            Amount = 21f,
                            IvoiceID = 1,
                            Price = 4.5f,
                            ProductName = "	Cookie Dough - Double	"
                        },
                        new
                        {
                            ID = 27,
                            Amount = 61f,
                            IvoiceID = 5,
                            Price = 72.58f,
                            ProductName = "	Beans - Fava Fresh	"
                        },
                        new
                        {
                            ID = 28,
                            Amount = 26f,
                            IvoiceID = 5,
                            Price = 21.42f,
                            ProductName = "	Broom And Brush Rack Black	"
                        },
                        new
                        {
                            ID = 29,
                            Amount = 45f,
                            IvoiceID = 4,
                            Price = 52.49f,
                            ProductName = "	Chivas Regal - 12 Year Old	"
                        },
                        new
                        {
                            ID = 30,
                            Amount = 93f,
                            IvoiceID = 3,
                            Price = 38.57f,
                            ProductName = "	Crackers - Water	"
                        },
                        new
                        {
                            ID = 31,
                            Amount = 99f,
                            IvoiceID = 4,
                            Price = 97.28f,
                            ProductName = "	Red Cod Fillets - 225g	"
                        },
                        new
                        {
                            ID = 32,
                            Amount = 18f,
                            IvoiceID = 1,
                            Price = 36.43f,
                            ProductName = "	Beans - Fine	"
                        },
                        new
                        {
                            ID = 33,
                            Amount = 7f,
                            IvoiceID = 1,
                            Price = 79.69f,
                            ProductName = "	Mix - Cocktail Ice Cream	"
                        },
                        new
                        {
                            ID = 34,
                            Amount = 18f,
                            IvoiceID = 3,
                            Price = 19.34f,
                            ProductName = "	Pasta - Rotini, Dry	"
                        },
                        new
                        {
                            ID = 35,
                            Amount = 94f,
                            IvoiceID = 4,
                            Price = 52.73f,
                            ProductName = "	Vinegar - White	"
                        },
                        new
                        {
                            ID = 36,
                            Amount = 82f,
                            IvoiceID = 4,
                            Price = 26.06f,
                            ProductName = "	Temperature Recording Station	"
                        },
                        new
                        {
                            ID = 37,
                            Amount = 72f,
                            IvoiceID = 5,
                            Price = 61.11f,
                            ProductName = "	Berry Brulee	"
                        },
                        new
                        {
                            ID = 38,
                            Amount = 69f,
                            IvoiceID = 1,
                            Price = 83.18f,
                            ProductName = "	Pesto - Primerba, Paste	"
                        },
                        new
                        {
                            ID = 39,
                            Amount = 98f,
                            IvoiceID = 4,
                            Price = 81.54f,
                            ProductName = "	Asparagus - White, Fresh	"
                        },
                        new
                        {
                            ID = 40,
                            Amount = 60f,
                            IvoiceID = 1,
                            Price = 57.39f,
                            ProductName = "	Soup - Campbells, Chix Gumbo	"
                        },
                        new
                        {
                            ID = 41,
                            Amount = 78f,
                            IvoiceID = 1,
                            Price = 69.58f,
                            ProductName = "	Oranges - Navel, 72	"
                        },
                        new
                        {
                            ID = 42,
                            Amount = 86f,
                            IvoiceID = 2,
                            Price = 58f,
                            ProductName = "	Chocolate - Pistoles, Lactee, Milk	"
                        },
                        new
                        {
                            ID = 43,
                            Amount = 24f,
                            IvoiceID = 4,
                            Price = 81.02f,
                            ProductName = "	Wine - Alsace Gewurztraminer	"
                        },
                        new
                        {
                            ID = 44,
                            Amount = 52f,
                            IvoiceID = 3,
                            Price = 38.11f,
                            ProductName = "	Nantucket - Pomegranate Pear	"
                        },
                        new
                        {
                            ID = 45,
                            Amount = 22f,
                            IvoiceID = 3,
                            Price = 73.08f,
                            ProductName = "	Spice - Peppercorn Melange	"
                        },
                        new
                        {
                            ID = 46,
                            Amount = 41f,
                            IvoiceID = 2,
                            Price = 49.56f,
                            ProductName = "	Sobe - Lizard Fuel	"
                        },
                        new
                        {
                            ID = 47,
                            Amount = 73f,
                            IvoiceID = 3,
                            Price = 87.54f,
                            ProductName = "	Container - Foam Dixie 12 Oz	"
                        },
                        new
                        {
                            ID = 48,
                            Amount = 3f,
                            IvoiceID = 3,
                            Price = 50.02f,
                            ProductName = "	Wine - Red, Colio Cabernet	"
                        },
                        new
                        {
                            ID = 49,
                            Amount = 43f,
                            IvoiceID = 2,
                            Price = 80.98f,
                            ProductName = "	Cheese - Le Cheve Noir	"
                        },
                        new
                        {
                            ID = 50,
                            Amount = 25f,
                            IvoiceID = 2,
                            Price = 71.98f,
                            ProductName = "	Fish - Atlantic Salmon, Cold	"
                        },
                        new
                        {
                            ID = 51,
                            Amount = 20f,
                            IvoiceID = 2,
                            Price = 47.54f,
                            ProductName = "	Bagelers - Cinn / Brown Sugar	"
                        },
                        new
                        {
                            ID = 52,
                            Amount = 42f,
                            IvoiceID = 2,
                            Price = 48.76f,
                            ProductName = "	Chicken - Thigh, Bone In	"
                        },
                        new
                        {
                            ID = 53,
                            Amount = 14f,
                            IvoiceID = 4,
                            Price = 63.23f,
                            ProductName = "	Napkin - Cocktail,beige 2 - Ply	"
                        },
                        new
                        {
                            ID = 54,
                            Amount = 73f,
                            IvoiceID = 2,
                            Price = 72.63f,
                            ProductName = "	Phyllo Dough	"
                        },
                        new
                        {
                            ID = 55,
                            Amount = 35f,
                            IvoiceID = 3,
                            Price = 21.54f,
                            ProductName = "	Soup - Campbells - Tomato	"
                        },
                        new
                        {
                            ID = 56,
                            Amount = 98f,
                            IvoiceID = 4,
                            Price = 91.53f,
                            ProductName = "	V8 Pet	"
                        },
                        new
                        {
                            ID = 57,
                            Amount = 58f,
                            IvoiceID = 3,
                            Price = 59.88f,
                            ProductName = "	Stock - Chicken, White	"
                        },
                        new
                        {
                            ID = 58,
                            Amount = 44f,
                            IvoiceID = 1,
                            Price = 37.51f,
                            ProductName = "	Wine - Port Late Bottled Vintage	"
                        },
                        new
                        {
                            ID = 59,
                            Amount = 96f,
                            IvoiceID = 5,
                            Price = 17.84f,
                            ProductName = "	Beer - Sleemans Honey Brown	"
                        },
                        new
                        {
                            ID = 60,
                            Amount = 94f,
                            IvoiceID = 4,
                            Price = 42.47f,
                            ProductName = "	Wasabi Paste	"
                        },
                        new
                        {
                            ID = 61,
                            Amount = 100f,
                            IvoiceID = 4,
                            Price = 77.25f,
                            ProductName = "	Juice - Orangina	"
                        },
                        new
                        {
                            ID = 62,
                            Amount = 56f,
                            IvoiceID = 5,
                            Price = 19.46f,
                            ProductName = "	Wine - White, Antinore Orvieto	"
                        },
                        new
                        {
                            ID = 63,
                            Amount = 75f,
                            IvoiceID = 3,
                            Price = 36.87f,
                            ProductName = "	Lychee	"
                        },
                        new
                        {
                            ID = 64,
                            Amount = 11f,
                            IvoiceID = 2,
                            Price = 5.48f,
                            ProductName = "	Juice - Lemon	"
                        },
                        new
                        {
                            ID = 65,
                            Amount = 8f,
                            IvoiceID = 1,
                            Price = 77.66f,
                            ProductName = "	Cup - 8oz Coffee Perforated	"
                        },
                        new
                        {
                            ID = 66,
                            Amount = 63f,
                            IvoiceID = 3,
                            Price = 42.36f,
                            ProductName = "	Seaweed Green Sheets	"
                        },
                        new
                        {
                            ID = 67,
                            Amount = 58f,
                            IvoiceID = 5,
                            Price = 95.07f,
                            ProductName = "	Syrup - Pancake	"
                        },
                        new
                        {
                            ID = 68,
                            Amount = 10f,
                            IvoiceID = 5,
                            Price = 28.9f,
                            ProductName = "	Veal - Bones	"
                        },
                        new
                        {
                            ID = 69,
                            Amount = 26f,
                            IvoiceID = 5,
                            Price = 18.31f,
                            ProductName = "	Nut - Pumpkin Seeds	"
                        },
                        new
                        {
                            ID = 70,
                            Amount = 21f,
                            IvoiceID = 5,
                            Price = 89.4f,
                            ProductName = "	Napkin White - Starched	"
                        },
                        new
                        {
                            ID = 71,
                            Amount = 72f,
                            IvoiceID = 5,
                            Price = 14.04f,
                            ProductName = "	Wine - George Duboeuf Rose	"
                        },
                        new
                        {
                            ID = 72,
                            Amount = 36f,
                            IvoiceID = 4,
                            Price = 99.16f,
                            ProductName = "	Onion - Dried	"
                        },
                        new
                        {
                            ID = 73,
                            Amount = 72f,
                            IvoiceID = 5,
                            Price = 23.76f,
                            ProductName = "	Sprouts Dikon	"
                        },
                        new
                        {
                            ID = 74,
                            Amount = 7f,
                            IvoiceID = 5,
                            Price = 28.48f,
                            ProductName = "	Melon - Watermelon, Seedless	"
                        },
                        new
                        {
                            ID = 75,
                            Amount = 41f,
                            IvoiceID = 1,
                            Price = 4.81f,
                            ProductName = "	Cucumber - English	"
                        },
                        new
                        {
                            ID = 76,
                            Amount = 94f,
                            IvoiceID = 4,
                            Price = 74.74f,
                            ProductName = "	Muffin Carrot - Individual	"
                        },
                        new
                        {
                            ID = 77,
                            Amount = 57f,
                            IvoiceID = 2,
                            Price = 47.1f,
                            ProductName = "	Soup - Knorr, Ministrone	"
                        },
                        new
                        {
                            ID = 78,
                            Amount = 37f,
                            IvoiceID = 3,
                            Price = 26.21f,
                            ProductName = "	Halibut - Fletches	"
                        },
                        new
                        {
                            ID = 79,
                            Amount = 14f,
                            IvoiceID = 2,
                            Price = 41.65f,
                            ProductName = "	Sachet	"
                        },
                        new
                        {
                            ID = 80,
                            Amount = 25f,
                            IvoiceID = 3,
                            Price = 78.32f,
                            ProductName = "	Oil - Avocado	"
                        },
                        new
                        {
                            ID = 81,
                            Amount = 63f,
                            IvoiceID = 4,
                            Price = 62.63f,
                            ProductName = "	Coffee - French Vanilla Frothy	"
                        },
                        new
                        {
                            ID = 82,
                            Amount = 14f,
                            IvoiceID = 1,
                            Price = 61.45f,
                            ProductName = "	Lemon Grass	"
                        },
                        new
                        {
                            ID = 83,
                            Amount = 68f,
                            IvoiceID = 2,
                            Price = 40.33f,
                            ProductName = "	Nestea - Iced Tea	"
                        },
                        new
                        {
                            ID = 84,
                            Amount = 89f,
                            IvoiceID = 2,
                            Price = 5.22f,
                            ProductName = "	Cleaner - Pine Sol	"
                        },
                        new
                        {
                            ID = 85,
                            Amount = 87f,
                            IvoiceID = 5,
                            Price = 77.8f,
                            ProductName = "	Chips - Assorted	"
                        },
                        new
                        {
                            ID = 86,
                            Amount = 59f,
                            IvoiceID = 4,
                            Price = 74.67f,
                            ProductName = "	Squid Ink	"
                        },
                        new
                        {
                            ID = 87,
                            Amount = 6f,
                            IvoiceID = 1,
                            Price = 20.95f,
                            ProductName = "	Flower - Daisies	"
                        },
                        new
                        {
                            ID = 88,
                            Amount = 46f,
                            IvoiceID = 3,
                            Price = 89.72f,
                            ProductName = "	Pork - Belly Fresh	"
                        },
                        new
                        {
                            ID = 89,
                            Amount = 98f,
                            IvoiceID = 4,
                            Price = 58.51f,
                            ProductName = "	Arctic Char - Fresh, Whole	"
                        },
                        new
                        {
                            ID = 90,
                            Amount = 48f,
                            IvoiceID = 2,
                            Price = 18.61f,
                            ProductName = "	Cakes Assorted	"
                        },
                        new
                        {
                            ID = 91,
                            Amount = 48f,
                            IvoiceID = 1,
                            Price = 20.79f,
                            ProductName = "	Table Cloth - 53x69 Colour	"
                        },
                        new
                        {
                            ID = 92,
                            Amount = 55f,
                            IvoiceID = 4,
                            Price = 30f,
                            ProductName = "	Cheese - Brie Roitelet	"
                        },
                        new
                        {
                            ID = 93,
                            Amount = 79f,
                            IvoiceID = 5,
                            Price = 16.36f,
                            ProductName = "	Wine - Cotes Du Rhone Parallele	"
                        },
                        new
                        {
                            ID = 94,
                            Amount = 94f,
                            IvoiceID = 5,
                            Price = 18.8f,
                            ProductName = "	Juice - Clam, 46 Oz	"
                        },
                        new
                        {
                            ID = 95,
                            Amount = 67f,
                            IvoiceID = 2,
                            Price = 50.93f,
                            ProductName = "	Smoked Paprika	"
                        },
                        new
                        {
                            ID = 96,
                            Amount = 52f,
                            IvoiceID = 3,
                            Price = 8.28f,
                            ProductName = "	Steampan - Half Size Shallow	"
                        },
                        new
                        {
                            ID = 97,
                            Amount = 20f,
                            IvoiceID = 5,
                            Price = 85.42f,
                            ProductName = "	Pail With Metal Handle 16l White	"
                        },
                        new
                        {
                            ID = 98,
                            Amount = 76f,
                            IvoiceID = 2,
                            Price = 7.12f,
                            ProductName = "	Flour - Buckwheat, Dark	"
                        },
                        new
                        {
                            ID = 99,
                            Amount = 29f,
                            IvoiceID = 5,
                            Price = 68.14f,
                            ProductName = "	Bagel - Whole White Sesame	"
                        },
                        new
                        {
                            ID = 100,
                            Amount = 31f,
                            IvoiceID = 4,
                            Price = 26.09f,
                            ProductName = "	Bread - Sticks, Thin, Plain	"
                        },
                        new
                        {
                            ID = 101,
                            Amount = 93f,
                            IvoiceID = 4,
                            Price = 81.67f,
                            ProductName = "	Pumpkin	"
                        },
                        new
                        {
                            ID = 102,
                            Amount = 80f,
                            IvoiceID = 3,
                            Price = 48.09f,
                            ProductName = "	Carbonated Water - Blackberry	"
                        },
                        new
                        {
                            ID = 103,
                            Amount = 45f,
                            IvoiceID = 1,
                            Price = 44.76f,
                            ProductName = "	Muffins - Assorted	"
                        },
                        new
                        {
                            ID = 104,
                            Amount = 76f,
                            IvoiceID = 2,
                            Price = 84.54f,
                            ProductName = "	Lettuce - Baby Salad Greens	"
                        },
                        new
                        {
                            ID = 105,
                            Amount = 20f,
                            IvoiceID = 2,
                            Price = 8.17f,
                            ProductName = "	Oil - Sunflower	"
                        },
                        new
                        {
                            ID = 106,
                            Amount = 76f,
                            IvoiceID = 4,
                            Price = 28.36f,
                            ProductName = "	Veal - Round, Eye Of	"
                        },
                        new
                        {
                            ID = 107,
                            Amount = 25f,
                            IvoiceID = 5,
                            Price = 66.08f,
                            ProductName = "	Flour - Strong	"
                        },
                        new
                        {
                            ID = 108,
                            Amount = 11f,
                            IvoiceID = 5,
                            Price = 77.99f,
                            ProductName = "	Wine - Magnotta, Merlot Sr Vqa	"
                        },
                        new
                        {
                            ID = 109,
                            Amount = 2f,
                            IvoiceID = 2,
                            Price = 48.58f,
                            ProductName = "	Chocolate - Semi Sweet	"
                        },
                        new
                        {
                            ID = 110,
                            Amount = 99f,
                            IvoiceID = 2,
                            Price = 81.33f,
                            ProductName = "	Pepper - Green Thai	"
                        },
                        new
                        {
                            ID = 111,
                            Amount = 28f,
                            IvoiceID = 5,
                            Price = 57.48f,
                            ProductName = "	Cheese - Woolwich Goat, Log	"
                        },
                        new
                        {
                            ID = 112,
                            Amount = 11f,
                            IvoiceID = 2,
                            Price = 14.03f,
                            ProductName = "	Muffin Batt - Carrot Spice	"
                        },
                        new
                        {
                            ID = 113,
                            Amount = 99f,
                            IvoiceID = 1,
                            Price = 38.98f,
                            ProductName = "	Bread - Bistro Sour	"
                        },
                        new
                        {
                            ID = 114,
                            Amount = 94f,
                            IvoiceID = 2,
                            Price = 98.08f,
                            ProductName = "	Rice - Brown	"
                        },
                        new
                        {
                            ID = 115,
                            Amount = 29f,
                            IvoiceID = 3,
                            Price = 40.92f,
                            ProductName = "	Pears - Anjou	"
                        },
                        new
                        {
                            ID = 116,
                            Amount = 59f,
                            IvoiceID = 2,
                            Price = 54.2f,
                            ProductName = "	Flour - Corn, Fine	"
                        },
                        new
                        {
                            ID = 117,
                            Amount = 20f,
                            IvoiceID = 4,
                            Price = 87.87f,
                            ProductName = "	Water - Perrier	"
                        },
                        new
                        {
                            ID = 118,
                            Amount = 6f,
                            IvoiceID = 1,
                            Price = 25.74f,
                            ProductName = "	Gelatine Leaves - Envelopes	"
                        },
                        new
                        {
                            ID = 119,
                            Amount = 8f,
                            IvoiceID = 1,
                            Price = 46.43f,
                            ProductName = "	Muffin Batt - Carrot Spice	"
                        },
                        new
                        {
                            ID = 120,
                            Amount = 34f,
                            IvoiceID = 4,
                            Price = 73.94f,
                            ProductName = "	Phyllo Dough	"
                        },
                        new
                        {
                            ID = 121,
                            Amount = 3f,
                            IvoiceID = 5,
                            Price = 23.32f,
                            ProductName = "	Pears - Bosc	"
                        },
                        new
                        {
                            ID = 122,
                            Amount = 22f,
                            IvoiceID = 2,
                            Price = 76.17f,
                            ProductName = "	Sauce - Fish 25 Ozf Bottle	"
                        },
                        new
                        {
                            ID = 123,
                            Amount = 22f,
                            IvoiceID = 2,
                            Price = 83.75f,
                            ProductName = "	Strawberries - California	"
                        },
                        new
                        {
                            ID = 124,
                            Amount = 82f,
                            IvoiceID = 2,
                            Price = 47.63f,
                            ProductName = "	Pasta - Tortellini, Fresh	"
                        },
                        new
                        {
                            ID = 125,
                            Amount = 27f,
                            IvoiceID = 3,
                            Price = 59.11f,
                            ProductName = "	Beef - Montreal Smoked Brisket	"
                        },
                        new
                        {
                            ID = 126,
                            Amount = 84f,
                            IvoiceID = 4,
                            Price = 83.06f,
                            ProductName = "	Cookies Cereal Nut	"
                        },
                        new
                        {
                            ID = 127,
                            Amount = 60f,
                            IvoiceID = 4,
                            Price = 62.41f,
                            ProductName = "	Worcestershire Sauce	"
                        },
                        new
                        {
                            ID = 128,
                            Amount = 72f,
                            IvoiceID = 2,
                            Price = 16.46f,
                            ProductName = "	Wine - Barbera Alba Doc 2001	"
                        },
                        new
                        {
                            ID = 129,
                            Amount = 30f,
                            IvoiceID = 2,
                            Price = 83.7f,
                            ProductName = "	Venison - Striploin	"
                        },
                        new
                        {
                            ID = 130,
                            Amount = 55f,
                            IvoiceID = 4,
                            Price = 26.29f,
                            ProductName = "	Galliano	"
                        },
                        new
                        {
                            ID = 131,
                            Amount = 74f,
                            IvoiceID = 1,
                            Price = 72.52f,
                            ProductName = "	Bread - Flat Bread	"
                        },
                        new
                        {
                            ID = 132,
                            Amount = 96f,
                            IvoiceID = 4,
                            Price = 54.55f,
                            ProductName = "	Soap - Hand Soap	"
                        },
                        new
                        {
                            ID = 133,
                            Amount = 47f,
                            IvoiceID = 4,
                            Price = 46.02f,
                            ProductName = "	Tomatoes - Yellow Hot House	"
                        },
                        new
                        {
                            ID = 134,
                            Amount = 27f,
                            IvoiceID = 3,
                            Price = 86.08f,
                            ProductName = "	Milk 2% 500 Ml	"
                        },
                        new
                        {
                            ID = 135,
                            Amount = 16f,
                            IvoiceID = 2,
                            Price = 43.96f,
                            ProductName = "	Glove - Cutting	"
                        },
                        new
                        {
                            ID = 136,
                            Amount = 74f,
                            IvoiceID = 3,
                            Price = 5.07f,
                            ProductName = "	Cake - Pancake	"
                        });
                });

            modelBuilder.Entity("LAB1.Models.InvoiceModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InvoiceModelID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("InvoiceModelID");

                    b.HasIndex("UserID");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "Fairview 5451, New Orleans - 6420, The Bahamas",
                            Date = new DateTime(2022, 3, 8, 13, 17, 20, 78, DateTimeKind.Local).AddTicks(6003),
                            UserID = 1
                        },
                        new
                        {
                            ID = 2,
                            Address = "Garland - 2327, Dominican Republic",
                            Date = new DateTime(2022, 3, 8, 13, 17, 20, 83, DateTimeKind.Local).AddTicks(8240),
                            UserID = 1
                        },
                        new
                        {
                            ID = 3,
                            Address = "Ellerslie 5206, Wien - 7026, Morocco",
                            Date = new DateTime(2022, 3, 8, 13, 17, 20, 83, DateTimeKind.Local).AddTicks(8279),
                            UserID = 2
                        },
                        new
                        {
                            ID = 4,
                            Address = "Garfield 8152, Cincinnati - 6755, Djibouti",
                            Date = new DateTime(2022, 3, 8, 13, 17, 20, 83, DateTimeKind.Local).AddTicks(8294),
                            UserID = 1
                        },
                        new
                        {
                            ID = 5,
                            Address = "Chesterfield  3014, Columbus - 2530, Grenada",
                            Date = new DateTime(2022, 3, 8, 13, 17, 20, 83, DateTimeKind.Local).AddTicks(8308),
                            UserID = 1
                        });
                });

            modelBuilder.Entity("LAB1.Models.RoleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "1a5974b6-190e-4485-8d84-3ee4725be252",
                            Name = "ADMIN",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "0b37a46d-a69e-4925-8e3b-71da129ef802",
                            Name = "USER",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("LAB1.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "090df916-32b0-4c85-b56c-00f740e5a12b",
                            Email = "adam@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "adam@example.com",
                            NormalizedUserName = "Adam Nowak",
                            PasswordHash = "vCBk9YvE1nySW0iK0xsk8zfdfuo=",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "Adam Nowak"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f8e26a78-3bf3-42d3-8091-92f71e69ff6d",
                            Email = "jan@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "jan@example.com",
                            NormalizedUserName = "Jan Nowak",
                            PasswordHash = "/hQQQoX8WPWsR+ize8w/488lNDE=",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "Jan Nowak"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("LAB1.Models.InvoiceItemModel", b =>
                {
                    b.HasOne("LAB1.Models.InvoiceModel", "Ivoice")
                        .WithMany()
                        .HasForeignKey("IvoiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ivoice");
                });

            modelBuilder.Entity("LAB1.Models.InvoiceModel", b =>
                {
                    b.HasOne("LAB1.Models.InvoiceModel", null)
                        .WithMany("Invoices")
                        .HasForeignKey("InvoiceModelID");

                    b.HasOne("LAB1.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("LAB1.Models.RoleModel", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("LAB1.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("LAB1.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("LAB1.Models.RoleModel", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LAB1.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("LAB1.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LAB1.Models.InvoiceModel", b =>
                {
                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
